[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
camerax = "1.5.2"
hilt = "2.57.2"
ksp = "2.0.21-1.0.27"
googleGmsGoogleServices = "4.4.4"
firebaseAnalytics = "23.0.0"
permissions = "0.32.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

camerax-core = {group = "androidx.camera", name = "camera-core", version.ref = "camerax"}
camerax-camera2 = {group = "androidx.camera", name = "camera-camera2", version.ref = "camerax"}
camerax-lifecycle = {group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax"}
camerax-view = {group = "androidx.camera", name = "camera-view", version.ref = "camerax"}

#Permissions
permissions =  { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "permissions" }

#hilt
hilt-android =  { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler =  { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
#hilt-navigation =  { group = "com.google.dagger", name = "hilt-android-navigation", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.3.0" }
hilt-compiler-x = { group = "androidx.hilt", name = "hilt-compiler", version = "1.3.0" }

#firebase
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#hilt
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }

#firebsae
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

